/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

/**
 *
 * @author DELL
 */
public class HRManagerSection extends javax.swing.JFrame {

    /**
     * Creates new form HRManagerSection
     */
    public HRManagerSection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddDepAndDes = new javax.swing.JButton();
        AddEmp = new javax.swing.JButton();
        SrchEmpDetails = new javax.swing.JButton();
        CrtHRAssiAcc = new javax.swing.JButton();
        HrManagerExit = new javax.swing.JButton();
        HRManagerbackBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("HR Manager Section");

        AddDepAndDes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddDepAndDes.setText("Add Departments And Destinations");
        AddDepAndDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDepAndDesActionPerformed(evt);
            }
        });

        AddEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddEmp.setText("Add Employees");
        AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpActionPerformed(evt);
            }
        });

        SrchEmpDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SrchEmpDetails.setText("Search Employee Details");
        SrchEmpDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchEmpDetailsActionPerformed(evt);
            }
        });

        CrtHRAssiAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CrtHRAssiAcc.setText("Create HR Assistance Account");
        CrtHRAssiAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrtHRAssiAccActionPerformed(evt);
            }
        });

        HrManagerExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HrManagerExit.setText("Exit");
        HrManagerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrManagerExitActionPerformed(evt);
            }
        });

        HRManagerbackBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HRManagerbackBTN.setText("Back");
        HRManagerbackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRManagerbackBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrtHRAssiAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SrchEmpDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddDepAndDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(HRManagerbackBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HrManagerExit)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(AddDepAndDes)
                        .addGap(18, 18, 18)
                        .addComponent(AddEmp)
                        .addGap(18, 18, 18)
                        .addComponent(SrchEmpDetails)
                        .addGap(18, 18, 18)
                        .addComponent(CrtHRAssiAcc)
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HrManagerExit)
                            .addComponent(HRManagerbackBTN))
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddDepAndDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDepAndDesActionPerformed
        // TODO add your handling code here:
        AddDepAndDes obj = new AddDepAndDes();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_AddDepAndDesActionPerformed

    private void AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpActionPerformed
        // TODO add your handling code here:
        AddEmployees obj = new AddEmployees();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_AddEmpActionPerformed

    private void SrchEmpDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrchEmpDetailsActionPerformed
        // TODO add your handling code here:
        SearchEmployeeDetails obj = new SearchEmployeeDetails();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_SrchEmpDetailsActionPerformed

    private void CrtHRAssiAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrtHRAssiAccActionPerformed
        // TODO add your handling code here:
        CreateHRAssistantAccount obj = new CreateHRAssistantAccount();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_CrtHRAssiAccActionPerformed

    private void HrManagerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrManagerExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_HrManagerExitActionPerformed

    private void HRManagerbackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRManagerbackBTNActionPerformed
        // TODO add your handling code here:
        MainDashbord obj = new MainDashbord();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_HRManagerbackBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRManagerSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRManagerSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRManagerSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRManagerSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManagerSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDepAndDes;
    private javax.swing.JButton AddEmp;
    private javax.swing.JButton CrtHRAssiAcc;
    private javax.swing.JButton HRManagerbackBTN;
    private javax.swing.JButton HrManagerExit;
    private javax.swing.JButton SrchEmpDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
